### ISSUE TITLE
Update reporter to work with Chrome

### ISSUE THREAD

**Issue by mscharp** [sandermak/jasmine2-junit#6]
We recently updated our e2e tests to use jasmine2, and were looking for a new junit reporter for our tests when I came across your port.  I'd like to use it, unfortunately our CI builds run the e2e tests against Chrome, which isn't supported just yet.

I'd be happy to take a look in extending the functionality, but have don't really know where to start or what needs to be added.  If you could provide some insight, maybe through a few PRs we could get this functionality added.

Thanks

**Comment by sandermak** [comment]
Hi,

Thanks for commenting. Unfortunately what you want is not really going to work. Graphical browsers like Chrome don't have file-access capabilities and can therefore not write JUnit xml files. We use this plugin for Jasmine unit tests that can be run using a headless browser (such as PhantomJS), which *can* access the file system.

Some e2e testrunners (like Protractor) do support writing JUnit xml output. But those write the results from the testdriver, not the browser that is executing the tests afaik.

**Comment by mscharp** [comment]
Ok thanks.  We are using protractor so it sounds like it is a possibility (somehow).  From your experience, would that functionality be added by doing something similar to what you've done here, or should I talk with the protractor folks?

**Comment by sandermak** [comment]
Should work out-of-the-box, see last comment on this issue: https://github.com/angular/protractor/issues/60

Good luck!

**Comment by mscharp** [comment]
Hey, this was perfect!  Thank's for taking the time to help me find this solution (which should be documented better on Protractor's site, imo).
