### ISSUE TITLE
Length of argument list of phantom 

### ISSUE THREAD

**Issue by StefanPerez** [sandermak/jasmine2-junit#8]
I got a problem generating these XML files. When I run my specrunner.html with phantom I get the following message:

`TypeError: undefined is not an object (evaluating 'phantom.args.length')
jasmine2-runner.js:3 in global code`

Which I can fix if I change the phantom.args to system.arg and create on top a variable for the system.

But if I run that I will get the following result:

`Jasmine ran in  1.873  seconds
3 specs, 0 failures
Page has timed out; aborting.`

I can not find out why my page is timed out. Can you perhaps guide me how I can solve it? The XML is generated so that works but it is not filled with any data.

Extra information:
If I add `console.log(filename,output);` to line 185 of jasmine2-runner.js this is what it will output:
.\unittesting.xml undefined

I guess the output is not known and therefore the page has timed out, is that right?

Environment: PhantomJS 2.0 (windows) - Jasmine 2.3.4

**Comment by sandermak** [comment]
Which version of PhantomJS are you running this with? I've tested this with Phantom 1.9.x, 2.x is unfortunately not supported (too many API changes). I'd advise also to have a look at https://github.com/larrymyers/jasmine-reporters, they have support for Jasmine 2 now as well and it has more active contributors.

**Comment by StefanPerez** [comment]
Look at my updated question!

**Comment by sandermak** [comment]
Thanks for the info, so this not working with Phantom 2.x is expected. I started looking into supporting 2.x, but there were too many API changes for me to fix it in a reasonable timeframe. I either recommend checking out the other project I mentioned, or would be happy to look at a PR to support Phantom 2.x in addition to 1.9.x. Unfortunately I don't have the time (and need) to do this currently.

**Comment by sandermak** [comment]
I'll also update the README to reflect this info.

**Comment by StefanPerez** [comment]
No problem! Thanks for the fast answer! :+1:
